-- 테스트 데이터 초기화 스크립트
-- 애플리케이션 시작 시 자동 실행됨 (defer-datasource-initialization: true)

-- 게시글 데이터 (50개)
INSERT INTO posts (title, content, author, created_at, updated_at)
VALUES ('Kotlin 학습 가이드', 'Kotlin을 배우는 방법에 대한 포스트입니다. 기본 문법부터 고급 기능까지 다룹니다.', '김개발',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Spring Boot와 Kotlin', 'Spring Boot에서 Kotlin을 사용하는 방법을 상세히 설명합니다.', '이코틀린',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Coroutines 완벽 가이드', 'Kotlin Coroutines를 마스터하는 방법. 비동기 프로그래밍의 핵심입니다.', '박비동기',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('QueryDSL 활용법', 'QueryDSL로 타입 안전한 쿼리 작성하기. JPA와의 완벽한 조화.', '최쿼리', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('JPA Entity 설계', 'JPA Entity를 Kotlin으로 설계하는 방법과 best practice.', '정엔티티', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Docker로 배포하기', 'Docker와 Docker Compose를 활용한 배포 전략', '도커맨', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Kotlin DSL 마스터하기', 'Kotlin의 강력한 DSL 기능을 활용하는 방법', 'DSL마스터', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('AWS EC2 배포 가이드', 'AWS EC2에 Spring Boot 애플리케이션 배포하기', '클라우드', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('GitHub Actions CI/CD', 'GitHub Actions로 자동 배포 파이프라인 구축', 'CI/CD전문가', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('MySQL 최적화 팁', 'MySQL 데이터베이스 성능 최적화 방법', 'DB튜너', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Redis 캐싱 전략', 'Redis를 활용한 효율적인 캐싱 구현', '캐시마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('REST API 설계 원칙', 'RESTful API 설계 시 지켜야 할 원칙들', 'API설계자', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Swagger 문서화', 'Swagger를 이용한 API 문서 자동화', '문서왕', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('JUnit5 테스트 전략', 'JUnit5로 효과적인 단위 테스트 작성하기', '테스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mockito 활용법', 'Mockito를 활용한 목 객체 테스트', '목킹전문가', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Spring Security 인증', 'Spring Security로 JWT 인증 구현하기', '보안전문가', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Kafka 메시징', 'Apache Kafka를 이용한 메시지 큐 구현', '메시지마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Gradle 멀티모듈', 'Gradle 멀티모듈 프로젝트 구성하기', '빌드마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Kotlin Collection 활용', 'Kotlin Collection API 완벽 가이드', '컬렉션왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('sealed class 활용', 'Kotlin sealed class로 타입 안전성 확보', '타입세이프', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Extension Function 패턴', 'Extension Function을 활용한 코드 개선', '확장왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Null Safety 완벽 가이드', 'Kotlin의 null safety 기능 활용하기', '널안전', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Data Class 활용법', 'Data Class의 숨겨진 기능들', '데이터마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Companion Object 이해', 'Companion Object의 모든 것', '컴패니언', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('inline function 최적화', 'inline function으로 성능 최적화', '성능튜너', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Delegation 패턴', 'Kotlin의 위임 패턴 활용하기', '위임전문가', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Scope Function 가이드', 'let, run, apply, also, with 완벽 정리', '스코프마스터', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Sequence API 성능', 'Sequence로 대용량 데이터 처리 최적화', '시퀀스왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Reflection 활용', 'Kotlin Reflection API 사용법', '리플렉션', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Annotation Processing', 'Kotlin에서 annotation processor 만들기', '어노테이션', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Multiplatform 프로젝트', 'Kotlin Multiplatform으로 크로스플랫폼 개발', '멀티플랫폼', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Flow API 완벽 가이드', 'Kotlin Flow로 비동기 스트림 처리', '플로우마스터', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Channel 통신', 'Coroutine Channel을 이용한 통신 패턴', '채널왕', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('StateFlow vs SharedFlow', 'StateFlow와 SharedFlow의 차이점과 활용', '상태관리자', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Exception Handling', 'Kotlin에서의 예외 처리 best practice', '예외처리왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Transaction 관리', 'Spring Transaction 관리 전략', '트랜잭션', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lazy Initialization', 'lazy와 lateinit의 차이점', '지연초기화', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Property Delegate', 'Custom Property Delegate 만들기', '프로퍼티왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Type Alias 활용', 'typealias로 코드 가독성 향상', '타입별칭', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Smart Cast 이해', 'Kotlin의 스마트 캐스팅 완벽 이해', '캐스팅마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Contracts API', 'Kotlin Contracts로 컴파일러에게 힌트 주기', '계약전문가', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Object vs Companion', 'Object와 Companion Object 비교', '객체비교왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Generic 제약', 'Generic의 in, out, where 키워드', '제네릭마스터', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Reified Type Parameter', 'reified로 타입 정보 유지하기', '리파이드왕', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Infix Function 활용', 'infix function으로 DSL 만들기', '인픽스', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Operator Overloading', 'Kotlin의 연산자 오버로딩', '연산자왕', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Destructuring Declaration', '구조 분해 선언 활용 패턴', '구조분해', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Tailrec 최적화', 'tailrec으로 재귀 함수 최적화', '재귀마스터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Crossinline & Noinline', 'crossinline과 noinline 이해하기', '인라인전문가', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Kotlin 2.0 새 기능', 'Kotlin 2.0의 주요 변경사항', '최신트렌드', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

